local config = require("lapis.config")
return config("development", function()
  return postgres(function()
    host("127.0.0.1")
    user("username")
    password("")
    return database("personalisation")
  end)
end)
